global using System.Net;
global using System.Net.Http.Json;
global using Bogus;
global using Dapper;
global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Extensions.Configuration;
global using Npgsql;
global using Xunit;