name: ASP.NET 8 Build

on:
  push:
    branches:
      - "develop"

jobs:
  Build:
    name: Build .NET application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x" # Change to the version of .NET Core you need

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

  Integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: Build
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x" # Change to the version of .NET Core you need

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release
   
      - name: Test
        run: |
          mkdir scripts
          mv ./performance-monitoring/UserApi/tests/IntegrationTests/Fixtures/PostgreSql/PostgreSqlScript.sql ./scripts
          docker compose -f ./tests/IntegrationTests/docker-compose.yaml up -d
          dotnet test ./tests/IntegrationTests/*.csproj
