name: ASP.NET 8 Build

on:
  push:
    branches:
      - "develop"

jobs:
  Build:
    name: Build .NET application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x" # Change to the version of .NET Core you need

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

  # Integration-tests:
  #   name: Run integration tests
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 2
  #   needs: Build
    
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Setup .NET Core SDK
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: "8.x" # Change to the version of .NET Core you need

  #     - name: Restore dependencies
  #       run: dotnet restore

  #     - name: Build
  #       run: dotnet build --configuration Release
   
  #     - name: Test
  #       run: |
  #         mkdir scripts
  #         mv ./UserApi/tests/IntegrationTests/Fixtures/PostgreSql/PostgreSqlScript.sql ./scripts
  #         docker compose -f ./UserApi/tests/IntegrationTests/docker-compose.yaml up -d
  #         dotnet test ./UserApi/tests/IntegrationTests/*.csproj

  Performance-tests:
    name: Run performance tests
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: Build
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x" # Change to the version of .NET Core you need

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release
   
      - name: Install K6
        run: |
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
          
      - name: Test
        run: |
          mkdir scripts
          mv ./UserApi/tests/IntegrationTests/Fixtures/PostgreSql/PostgreSqlScript.sql ./scripts
          docker compose -f ./UserApi/tests/IntegrationTests/docker-compose.yaml up -d
          dotnet run --project ./UserApi/src/Api/Api.csproj > /dev/null &
          sleep 5
          k6 run ./UserApi/tests/PerformanceTests/GetAllUsersTest.js